<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.20" />
    <PackageReference Include="TUnit" Version="1.72.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Novolis.Templates.Microservice.Data\Novolis.Templates.Microservice.Data.csproj" />
    <ProjectReference Include="..\Novolis.Templates.Microservice\Novolis.Templates.Microservice.csproj" />
  </ItemGroup>
</Project>
