<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoBogus.NSubstitute" Version="2.13.1" />
    <PackageReference Include="AutoFixture.AutoNSubstitute" Version="4.18.0" />
    <PackageReference Include="RandomTestValues" Version="2.1.1" />
    <PackageReference Include="TUnit" Version="1.44.39" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Novolis.Templates.Microservice.Api\Novolis.Templates.Microservice.Api.csproj" />
    <ProjectReference Include="..\Novolis.Templates.Microservice.Client\Novolis.Templates.Microservice.Client.csproj" />
    <ProjectReference Include="..\Novolis.Templates.Microservice\Novolis.Templates.Microservice.csproj" />
  </ItemGroup>
</Project>
