<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Novolis.Templates.Microservice.Data.Migrations\Novolis.Templates.Microservice.Data.Migrations.csproj" />
    <ProjectReference Include="..\Novolis.Templates.Microservice.Data\Novolis.Templates.Microservice.Data.csproj" />
    <ProjectReference Include="..\Novolis.Templates.Microservice.Models\Novolis.Templates.Microservice.Models.csproj" />
    <ProjectReference Include="..\Novolis.Templates.Microservice\Novolis.Templates.Microservice.csproj" />
  </ItemGroup>
</Project>
