<Project>
  <Import Project="$(MSBuildThisFileDirectory)build\Novolis.Documentation.props"
          Condition="Exists('$(MSBuildThisFileDirectory)build\Novolis.Documentation.props')" />
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
</Project>
