<Project>
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props"
          Condition="Exists('$(MSBuildThisFileDirectory)..\Directory.Build.props')" />
  <Import Project="$(MSBuildThisFileDirectory)..\build\Novolis.Templates.Documentation.props"
          Condition="Exists('$(MSBuildThisFileDirectory)..\build\Novolis.Templates.Documentation.props')" />
  <Import Project="$(MSBuildThisFileDirectory)..\..\novolis-governance\build\Novolis.PackageReadme.props"
          Condition="Exists('$(MSBuildThisFileDirectory)..\..\novolis-governance\build\Novolis.PackageReadme.props')" />
</Project>
