<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Novolis.Templates.Microservice.Client</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Novolis.Templates.Microservice.Models\Novolis.Templates.Microservice.Models.csproj" />
  </ItemGroup>
</Project>
